name: Deploy CDK on Merge to Main

on:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install AWS CLI
        run: |
            if ! command -v aws &> /dev/null; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
            else
              echo "AWS CLI is already installed, skipping installation."
              sudo aws --version
            fi
        

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Zip Backend Folder
        run: |
          cd backend
          zip -r ../backend.zip .
          # Check if the backend.zip file was created successfully
          ls -l ../backend.zip

      - name: Install Dependencies
        run: |
          cd cdk
          npm install
          npm install -g aws-cdk

      - name: Run CDK Deployment
        run: |
          cd cdk
          ls -l
          cdk deploy --require-approval never backendZipPath=../backend.zip
